import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Topbar from "@/components/ui/topbar";
import "../globals.css";
import Footer from "@/components/ui/Footer";
import { ReduxProviders } from "@/lib/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard Layout",
  description: "Generated by create next app",
  icons: "favicon.png",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ReduxProviders>
          <Topbar />
          {children}
          <Footer />
        </ReduxProviders>
      </body>
    </html>
  );
}
