import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Topbar from "@/components/ui/topbar";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard Layout",
  description: "Generated by create next app",
  icons: "favicon.png",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Topbar />
        {children}
      </body>
    </html>
  );
}
